Portfolio
ZabihullahNooriWardak/Zabih-portfolio pull request #1
Opened 2023-06-05 15:39 UTC by ZabihullahNooriWardak

in this branch I started working on portfolio project and I have worked on these sections:
1 . HTML part
  ✌️ header 
  ✌️ body 
  ✌️ footer
2 . Css part
3 .linter configurations
4 . READMI.md file

2023-06-08 16:18 UTC, amon-cofie requested changes
Hi @ZabihullahNooriWardak , 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! 💪 

<img src="https://media0.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif"/>

## Highlights

🚀 Awesome first attempt
🚀 Your HTML file is well structured
🚀 Great styling
🚀 You used GitHub flow properly
🚀 You have no linter errors

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 16:18 UTC, amon-cofie commented on README.md
> +This project is [MIT](./LICENSE) licensed.
You have done great work on the readme file 👍. However, I notice that some of your headers don't show up properly. I think that the problem is that there is no spacing before the headings. Please add the spacing before the headings to make them appear as they are supposed to and make your documentation even more professional. In making this change, you would put some spacing: 
- Before line 121
- Before line 126
- Before line 130

Also, I suggest that you remove the ```'>'``` sign on line 123 so that your statement on that line shows up properly to make your readme look even more professional.

2023-06-08 16:18 UTC, amon-cofie commented on style.css
> +}
You have done excellent work on the styling 💪. However, let's talk a bit about best practices. One of the most important CSS best practices in my opinion is the preferred use of class selectors over id selectors when styling. This is obviously because of the reusability of class selectors which would make your CSS code DRY but the reason goes beyond that and I suggest that you checkout [Marcos's detailed article on hackernoon](https://hackernoon.com/why-ids-can-be-problematic-in-css-gt103uh6) to learn about this 😉. In that light, I suggest that you give your HTML elements class attributes and select those in your CSS for styling.

2023-06-08 16:18 UTC, amon-cofie commented on index.html
> +        <hr />
I think that using one of the heading tags like ```h2``` would be ideal. This would add a sort of hierarchy to the flow of the content of your page and hence make it more semantically sound 😉. In that light, I suggest that you change the ```p``` tag enclosing ```My Recent Works``` to an ```h2``` tag or lower if you feel. What do you think?

2023-06-08 16:18 UTC, amon-cofie commented on index.html
> +          </div>
Well done! these buttons are very well-positioned and structured 💪. However, let's talk semantics a bit. I believe that you would call these buttons a "list" of technologies used for the project right? I think we can code that very statement out by putting these buttons into a list (```ul``` and ```li```) 😉. This would make it more semantically sound. Your code might look something like this in the end: 

```sh
<ul class="button">
  <li><button class="html">HTML</button></li>
  <li><button>Bootstrap</button></li>
  <li><button>Ruby</button></li>
</ul>
```

2023-06-08 16:18 UTC, amon-cofie commented on style.css
> +}
The cards in the works section are laid out very well 👍 but the dimensions and spacing of the cards seem a bit off. I will leave screenshots below this comment so that you can visualize what I mean. I tried some tweaking and I think that you can get the cards to be centered in the middle of the page and then give them the required width according to the figma template (ie. 327px or the percentage of 327 of 375). In the end your code may look something like this: 

```sh
div.data-dashbord {
  margin-left: auto;
  margin-right: auto;
  background-image: url(images/availiability.png);
  width: 327px;
  background-size: cover;
  background-repeat: no-repeat;
  height: 43rem;
  display: flex;
  flex-direction: column;
  justify-content: flex-end;
  align-items: flex-start;
}
```

Your design: 
![image](https://github.com/ZabihullahNooriWardak/Zabih-portfolio/assets/107795045/870c5d24-f8a3-4204-bfbd-1bb7c1e85346)

Figma design: 
![image](https://github.com/ZabihullahNooriWardak/Zabih-portfolio/assets/107795045/2017504c-b51d-4a4d-8b2d-370958f88d39)

2023-06-08 16:18 UTC, amon-cofie commented on index.html
> +        <img src="images/f.png" alt="" />
It is always best to not add images that serve only to add to the background appearance as HTML elements. This is because anything in the HTML document counts as actual content of your webpage and would be considered by search engines in an attempt to find your page. I think that you should add these images in your CSS instead as background images. This helps greatly to improve your SEO scores 💪

2023-06-08 16:18 UTC, amon-cofie commented on index.html
> +          <p>
Just like in my previous comment about adding a heading to give the flow of  the content of your page a form of hierarchy, I think that you should change this p tag (line 212) to an h2 tag or lower to improve upon the semantics of your page

2023-06-09 09:11 UTC, Efiamotu-1 approved these changes
Hi @ZabihullahNooriWardak , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# STATUS: APPROVED 🕺🥳 

![giphy](https://user-images.githubusercontent.com/89055502/234114221-4ca295de-fd8f-4af6-9c49-a6d4c6ea67f7.gif)


## Highlights :dart: 
* Correct GitHub flow or Gitflow :heavy_check_mark: 
* Good commit messages :heavy_check_mark: 
* All linters passing :heavy_check_mark: 
* Good PR summary :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, you can now Merge since it is Approved ✅, However if there are any conflicts please resolve them before merging.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 10:43 UTC, ZabihullahNooriWardak commented
the portfolio feature branch adding to main branch

2023-06-09 10:44 UTC, merged

2023-06-10 00:30 UTC, ZabihullahNooriWardak commented
thank you so m

On Fri, 9 Jun 2023 at 13:41, Habeeb Efiamotu Musa Owolewa <
***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> Hi @ZabihullahNooriWardak <https://github.com/ZabihullahNooriWardak> ,
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
> STATUS: APPROVED 🕺🥳
>
> [image: giphy]
> <https://user-images.githubusercontent.com/89055502/234114221-4ca295de-fd8f-4af6-9c49-a6d4c6ea67f7.gif>
> Highlights 🎯
>
>    - Correct GitHub flow or Gitflow ✔️
>    - Good commit messages ✔️
>    - All linters passing ✔️
>    - Good PR summary ✔️
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
> Important Notes 📝
>
>    - Feel free to leave any questions or comments in the PR thread if
>    something is not 100% clear.
>    - Please, remember to tag me in your question so I can receive the
>    notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
>
> *Note:* Please, you can now Merge since it is Approved ✅, However if
> there are any conflicts please resolve them before merging.
>
> Thank you for your time 🙏 and call me if you need help or clarification
> ☎️
>
>    - This is My *GitHub*: [image: @Efiamotu-1]
>    <https://github.com/Efiamotu-1/>
>    - This is My *linkedIn*.[image: Habeeb Efiamotu Musa]
>    <https://www.linkedin.com/in/musa-habeeb/>
>    - This is My *Twitter*: [image: @EFYAMOTU]
>    <https://twitter.com/EFYAMOTU>
>    - This is My *Slack*: [image: Habeeb Efiamotu Musa] <https://slack.com>
>
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ZabihullahNooriWardak/Zabih-portfolio/pull/1#pullrequestreview-1471557859>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3O5GWPFZFGZ7WJTCDJF7ALXKLSDTANCNFSM6AAAAAAY3E3V54>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>

2023-06-10 00:32 UTC, ZabihullahNooriWardak commented
thank you so much if i need help I will be in contact with you .again
thanks For giving time

On Fri, 9 Jun 2023 at 13:41, Habeeb Efiamotu Musa Owolewa <
***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> Hi @ZabihullahNooriWardak <https://github.com/ZabihullahNooriWardak> ,
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
> STATUS: APPROVED 🕺🥳
>
> [image: giphy]
> <https://user-images.githubusercontent.com/89055502/234114221-4ca295de-fd8f-4af6-9c49-a6d4c6ea67f7.gif>
> Highlights 🎯
>
>    - Correct GitHub flow or Gitflow ✔️
>    - Good commit messages ✔️
>    - All linters passing ✔️
>    - Good PR summary ✔️
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
> Important Notes 📝
>
>    - Feel free to leave any questions or comments in the PR thread if
>    something is not 100% clear.
>    - Please, remember to tag me in your question so I can receive the
>    notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
>
> *Note:* Please, you can now Merge since it is Approved ✅, However if
> there are any conflicts please resolve them before merging.
>
> Thank you for your time 🙏 and call me if you need help or clarification
> ☎️
>
>    - This is My *GitHub*: [image: @Efiamotu-1]
>    <https://github.com/Efiamotu-1/>
>    - This is My *linkedIn*.[image: Habeeb Efiamotu Musa]
>    <https://www.linkedin.com/in/musa-habeeb/>
>    - This is My *Twitter*: [image: @EFYAMOTU]
>    <https://twitter.com/EFYAMOTU>
>    - This is My *Slack*: [image: Habeeb Efiamotu Musa] <https://slack.com>
>
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ZabihullahNooriWardak/Zabih-portfolio/pull/1#pullrequestreview-1471557859>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3O5GWPFZFGZ7WJTCDJF7ALXKLSDTANCNFSM6AAAAAAY3E3V54>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>

2024-10-01 13:11 UTC, ZabihullahNooriWardak commented
dddd