local Storage
ZabihullahNooriWardak/Zabih-portfolio pull request #22
Opened 2023-06-30 21:14 UTC by ZabihullahNooriWardak

in this branch  we worked on local storage for form text fields .

2023-06-30 21:42 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi Team 👋, 
![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)
Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Required Changes ♻️
_Please kindly check the comments under the review._

- Your commits


![image](https://github.com/ZabihullahNooriWardak/Zabih-portfolio/assets/78251927/42462ba0-9eb9-4f36-ab69-de448a3366a3)

[REQUIRED] - Please always use descriptive commit messages - each commit should be small enough to describe it in one sentence. 

The commit message should be written in the `imperative tense` and `capitalized`. [You can read more about how to write descriptive commit messages](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8).

- Here are some examples of descriptive commits:

![image](https://github.com/ZabihullahNooriWardak/Zabih-portfolio/assets/78251927/14472de6-a2db-4a48-b861-e0220364bc31)

🏮 As it is not easy to change commit history, please correct this behavior in the future. 👍

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-30 21:42 UTC, abdulhamiid commented on script.js
> +// console.log(localStorage.getItem('userData'));
To follow our [list of best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md), please do not commit old pieces of code as inline comments. They will make your project look messy. If you need to review a previous version of your code, you can always use git history. 🤗

2023-06-30 21:42 UTC, abdulhamiid commented on script.js
> +  };
According to the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/10_localstorage.md), please let's implement the following interactions and ensure that everything works fine. 💪

![image](https://github.com/ZabihullahNooriWardak/Zabih-portfolio/assets/78251927/90a605af-73db-4edb-88fd-6e4227828851)

Currently, your app is not working as expected, and the data from the `form` are not saved to the local storage. 👀

Error in the console
![image](https://github.com/ZabihullahNooriWardak/Zabih-portfolio/assets/78251927/1e133219-a4c8-4138-8fc1-d4f715c7d8c8)

Source
![image](https://github.com/ZabihullahNooriWardak/Zabih-portfolio/assets/78251927/53eac1f0-a768-42e3-b5da-e3cd3eb88820)

2023-07-01 02:30 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle: 

Hi @team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-01 02:30 UTC, Qoosim commented on script.js
> +  };
- [ ] Great work implementing required changes from the previous reviewer. However, there's one more thing you guys need to work on before your project could be approved. It is required that when the When the user loads the page, the code checks if there's any saved data in the local storage and if so the input fields are pre-filled with the data. What this means is that, if the user enters data into the form without submitting the form, when the user reload the page, the user's data should remain on the form. Kindly check below code for insight :point_down: 

```
    window.onload = () => {
      let savedFormData = localStorage.getItem('contactFormInput');
      savedFormData = JSON.parse(savedFormData);
      // Check if the form data object is found on localStorage
      if (savedFormData) {
        // populate inputs values if data was found
        // ex: nameInput.value = savedFormData.name
       }
    };

```

2023-07-01 03:56 UTC, skyv26 requested changes
## Hi @ZabihullahNooriWardak, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## STATUS: REQUIRE CHANGES 🔴 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOTljYjFhMDZmNmM4MTA2ZmNlOGEzY2E1ZjE5OWM3MDc5NzM5MGE0MyZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/2sGZ6lqDkf1HW1q0sk/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 
- Professional `README` template ✅ 
- Linters are green ✅ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

#### Cheers, and Happy coding!👏👏👏

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-01 03:56 UTC, skyv26 commented on script.js
> +  };
- [ ] Well done 👏🏻 , you did an awesome job by implementing the changes as per the previous code reviewer's request 👍🏻 but you guys still not following the things properly, you need to work on it before your project could be approved. It is required that when the user loads the page, the code checks if there are any saved data in the local storage and if so the input fields are pre-filled with the data. What this means is that, if the user enters data into the form without submitting the form, when the user reloads the page, the user's data should remain on the form. Kindly check the below code for insight 👇

```javascript
    window.onload = () => {
      let savedFormData = localStorage.getItem('contactFormInput');
      savedFormData = JSON.parse(savedFormData);
      // Check if the form data object is found on localStorage
      if (savedFormData) {
        // populate inputs values if data was found
        // ex: nameInput.value = savedFormData.name
       }
    };

```

### Video Demo For Understanding
[Screencast from 01-07-23 09:24:27 AM IST.webm](https://github.com/ZabihullahNooriWardak/Zabih-portfolio/assets/66476329/0e3904ac-fbf7-4ad5-9e1d-a422455d9567)

### Please resolve the below console error
![Screenshot from 2023-07-01 09-22-05](https://github.com/ZabihullahNooriWardak/Zabih-portfolio/assets/66476329/7e438c33-3ced-4292-b3f3-adf7a4ad4a6e)

2023-07-01 05:21 UTC, usorfaitheloho approved these changes
Hi @ZabihullahNooriWardak 👋,

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/l49JNZ87F3AmPoH0A/giphy.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-01 05:36 UTC, merged